// Mocks generated by Mockito 5.4.2 from annotations
// in rideshare/test/features/pick_location/presentation/bloc/ride_request_bloc/ride_request_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rideshare/core/errors/failures.dart' as _i5;
import 'package:rideshare/features/pick_location/domain/entities/ride_offer.dart'
    as _i7;
import 'package:rideshare/features/pick_location/domain/entities/ride_request.dart'
    as _i6;
import 'package:rideshare/features/pick_location/domain/usecases/ride_request_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetRideRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRideRequestUseCase extends _i1.Mock
    implements _i3.GetRideRequestUseCase {
  MockGetRideRequestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i4.Stream<_i6.RideRequest>>> call(
          _i7.RideOffer? passenger) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [passenger],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, _i4.Stream<_i6.RideRequest>>>.value(
            _FakeEither_0<_i5.Failure, _i4.Stream<_i6.RideRequest>>(
          this,
          Invocation.method(
            #call,
            [passenger],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i4.Stream<_i6.RideRequest>>>);
}
