// Mocks generated by Mockito 5.4.2 from annotations
// in rideshare/test/features/authentication/data/repositories/authentication_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rideshare/features/authentication/data/datasources/auth_remote_datasource.dart'
    as _i3;
import 'package:rideshare/features/authentication/data/models/user_profile_model.dart'
    as _i2;
import 'package:rideshare/features/authentication/domain/entities/signup_payload.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfileModel_0 extends _i1.SmartFake
    implements _i2.UserProfileModel {
  _FakeUserProfileModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i3.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> verifyOtp(
    String? phoneNumber,
    String? otp,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [
            phoneNumber,
            otp,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.UserProfileModel> signup(_i5.SignupPayload? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [model],
        ),
        returnValue:
            _i4.Future<_i2.UserProfileModel>.value(_FakeUserProfileModel_0(
          this,
          Invocation.method(
            #signup,
            [model],
          ),
        )),
      ) as _i4.Future<_i2.UserProfileModel>);
}
