// Mocks generated by Mockito 5.4.2 from annotations
// in rideshare/test/features/pick_location/data/repositories/destination_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rideshare/core/network/network_info.dart' as _i5;
import 'package:rideshare/features/pick_location/data/datasources/destination_datasource.dart'
    as _i2;
import 'package:rideshare/features/pick_location/domain/entities/destination.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DestinationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDestinationDataSource extends _i1.Mock
    implements _i2.DestinationDataSource {
  MockDestinationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Destination>> fetchPassengerHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPassengerHistory,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.Destination>>.value(<_i4.Destination>[]),
      ) as _i3.Future<List<_i4.Destination>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
