// Mocks generated by Mockito 5.4.1 from annotations
// in rideshare/test/features/location/domain/usecase/location_usecase_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rideshare/core/errors/failures.dart' as _i5;
import 'package:rideshare/features/feeds/domain/entity/location.dart'
    as _i6;
import 'package:rideshare/features/feeds/domain/repository/location_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationRepository extends _i1.Mock
    implements _i3.LocationRepository {
  MockLocationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Location>> getLocation(
          String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [cityName],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Location>>.value(
            _FakeEither_0<_i5.Failure, _i6.Location>(
          this,
          Invocation.method(
            #getLocation,
            [cityName],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Location>>);
}
