// Mocks generated by Mockito 5.4.2 from annotations
// in rideshare/test/features/pick_location/data/datasources/ride_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rideshare/features/pick_location/data/datasources/ride_request_api_provider.dart'
    as _i3;
import 'package:rideshare/features/pick_location/domain/entities/ride_offer.dart'
    as _i6;
import 'package:rideshare/features/pick_location/domain/entities/ride_request.dart'
    as _i5;
import 'package:signalr_core/signalr_core.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHubConnection_0 extends _i1.SmartFake implements _i2.HubConnection {
  _FakeHubConnection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RideRequestApiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRideRequestApiProvider extends _i1.Mock
    implements _i3.RideRequestApiProvider {
  MockRideRequestApiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);
  @override
  _i2.HubConnection get hubConnection => (super.noSuchMethod(
        Invocation.getter(#hubConnection),
        returnValue: _FakeHubConnection_0(
          this,
          Invocation.getter(#hubConnection),
        ),
      ) as _i2.HubConnection);
  @override
  set hubConnection(_i2.HubConnection? _hubConnection) => super.noSuchMethod(
        Invocation.setter(
          #hubConnection,
          _hubConnection,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> setupHubConnection() => (super.noSuchMethod(
        Invocation.method(
          #setupHubConnection,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i4.Stream<_i5.RideRequest>> getRideRequestsForPassenger(
          _i6.RideOffer? passenger) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRideRequestsForPassenger,
          [passenger],
        ),
        returnValue: _i4.Future<_i4.Stream<_i5.RideRequest>>.value(
            _i4.Stream<_i5.RideRequest>.empty()),
      ) as _i4.Future<_i4.Stream<_i5.RideRequest>>);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
