// Mocks generated by Mockito 5.4.2 from annotations
// in rideshare/test/features/passenger_on_journey/data/datasources/ride_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rideshare/features/passenger_on_journey/data/datasource/ride_request_api_provider.dart'
    as _i4;
import 'package:rideshare/features/passenger_on_journey/domain/entities/ride_offer.dart'
    as _i7;
import 'package:rideshare/features/passenger_on_journey/domain/entities/ride_request.dart'
    as _i6;
import 'package:signalr_core/signalr_core.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHubConnection_0 extends _i1.SmartFake implements _i2.HubConnection {
  _FakeHubConnection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RideRequestApiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRideRequestApiProvider extends _i1.Mock
    implements _i4.RideRequestApiProvider {
  MockRideRequestApiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);
  @override
  _i2.HubConnection get hubConnection => (super.noSuchMethod(
        Invocation.getter(#hubConnection),
        returnValue: _FakeHubConnection_0(
          this,
          Invocation.getter(#hubConnection),
        ),
      ) as _i2.HubConnection);
  @override
  set hubConnection(_i2.HubConnection? _hubConnection) => super.noSuchMethod(
        Invocation.setter(
          #hubConnection,
          _hubConnection,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_1(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);
  @override
  set dio(_i3.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get token => (super.noSuchMethod(
        Invocation.getter(#token),
        returnValue: '',
      ) as String);
  @override
  _i5.Future<void> setupHubConnection() => (super.noSuchMethod(
        Invocation.method(
          #setupHubConnection,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<_i5.Stream<_i6.RideRequest>> getRideRequestsForPassenger(
          _i7.RideOffer? passenger) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRideRequestsForPassenger,
          [passenger],
        ),
        returnValue: _i5.Future<_i5.Stream<_i6.RideRequest>>.value(
            _i5.Stream<_i6.RideRequest>.empty()),
      ) as _i5.Future<_i5.Stream<_i6.RideRequest>>);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
